  basic_navigation[m
  bootstrap_4.6[m
  cart_add_gif[m
  controller[m
  develop[m
  develop_bug_game_init[m
  features/game_views1312[m
  features/jquery_navbar[m
  features/views[m
  game_init[m
  game_views1312[m
  giphy[m
  giphy_cart[m
  heroku[m
* [32mi18N[m
  items[m
  main[m
  release[m
  release_2[m
  sendgrid[m
  stage_giphy2[m
  stage_main_1[m
